name: Build Desktop Applications

on:
  push:
    branches:
      - main
      - 'preview_*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - windows-only
          - macos-only
  release:
    types: [created]

env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.11'
  RUST_VERSION: 'stable'

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'windows-only'
    
    env:
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: wasm32-unknown-unknown

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
          targets: wasm32-unknown-unknown

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: |
            frontend/node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install wasm-pack
        shell: pwsh
        run: |
          # Check if wasm-pack is already installed and working
          try {
            $version = wasm-pack --version 2>&1
            Write-Host "wasm-pack is already installed: $version"
          } catch {
            Write-Host "Installing wasm-pack..."
            cargo install wasm-pack
          }

      - name: Install Tauri CLI
        shell: pwsh
        run: |
          # Check if Tauri CLI is already installed
          $tauriPath = "$env:CARGO_HOME\bin\cargo-tauri.exe"
          if (Test-Path $tauriPath) {
            try {
              $version = & tauri --version 2>&1
              Write-Host "Tauri CLI is already installed: $version"
            } catch {
              Write-Host "Tauri CLI binary exists but may need reinstalling..."
              cargo install tauri-cli --force
            }
          } else {
            Write-Host "Installing Tauri CLI..."
            cargo install tauri-cli
          }

      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install

      - name: Build all components (WASM + Desktop)
        run: python build.py build-all

      - name: Sign Windows Executables
        if: env.WINDOWS_CERTIFICATE != '' && env.WINDOWS_CERTIFICATE != null
        env:
          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
        shell: pwsh
        run: |
          Write-Host "Starting code signing process..."
          
          # Decode certificate from base64
          try {
            $certBytes = [System.Convert]::FromBase64String($env:WINDOWS_CERTIFICATE)
            $certPath = "$env:TEMP\code-signing-cert.pfx"
            [System.IO.File]::WriteAllBytes($certPath, $certBytes)
            Write-Host "Certificate decoded successfully"
          } catch {
            Write-Host "Error decoding certificate: $_"
            exit 1
          }
          
          # Find all exe and msi files to sign
          $filesToSign = @()
          $filesToSign += Get-ChildItem -Path "target\release\bundle\msi" -Filter "*.msi" -ErrorAction SilentlyContinue
          $filesToSign += Get-ChildItem -Path "target\release\bundle\nsis" -Filter "*.exe" -ErrorAction SilentlyContinue
          
          if ($filesToSign.Count -eq 0) {
            Write-Host "Warning: No files found to sign"
          } else {
            foreach ($file in $filesToSign) {
              Write-Host "Signing: $($file.FullName)"
              & signtool sign /f "$certPath" /p "$env:WINDOWS_CERTIFICATE_PASSWORD" /t http://timestamp.digicert.com /fd sha256 "$($file.FullName)"
              if ($LASTEXITCODE -ne 0) {
                Write-Host "Warning: Failed to sign $($file.Name)"
              } else {
                Write-Host "Successfully signed: $($file.Name)"
              }
            }
          }
          
          # Clean up certificate file
          Remove-Item $certPath -Force
          Write-Host "Code signing completed"

      - name: Rename Windows artifacts
        run: |
          # Rename MSI to remove language suffix
          Get-ChildItem "target\release\bundle\msi\*.msi" | ForEach-Object {
            $newName = $_.Name -replace '_en-US', ''
            Rename-Item $_.FullName -NewName $newName
          }
          # List renamed files
          Get-ChildItem "target\release\bundle\msi\*.msi"
        shell: pwsh

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            target/release/bundle/
          retention-days: 7

      - name: Upload to Release (if release)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/bundle/msi/*.msi
            target/release/bundle/nsis/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'macos-only'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: wasm32-unknown-unknown

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
          targets: wasm32-unknown-unknown

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: |
            frontend/node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install wasm-pack
        run: |
          # Check if wasm-pack is already installed
          if command -v wasm-pack &> /dev/null; then
            echo "wasm-pack is already installed: $(wasm-pack --version)"
          else
            echo "Installing wasm-pack..."
            curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          fi

      - name: Install Tauri CLI
        run: |
          # Check if Tauri CLI is already installed
          if [ -f "$HOME/.cargo/bin/cargo-tauri" ]; then
            if tauri --version &> /dev/null 2>&1; then
              echo "Tauri CLI is already installed: $(tauri --version)"
            else
              echo "Tauri CLI binary exists but may need reinstalling..."
              cargo install tauri-cli --force
            fi
          else
            echo "Installing Tauri CLI..."
            cargo install tauri-cli
          fi

      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install

      - name: Build all components (WASM + Desktop)
        run: python3 build.py build-all

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            target/release/bundle/macos/*.app
            target/release/bundle/dmg/*.dmg
          retention-days: 7

      - name: Upload to Release (if release)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/bundle/dmg/*.dmg
            target/release/bundle/macos/*.app.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release-summary:
    name: Create Release Summary
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos]
    if: always() && (github.event_name == 'release' || github.event_name == 'workflow_dispatch' || github.event_name == 'push')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Generate checksums and summary
        run: |
          # Create summary file
          SUMMARY_FILE="build-summary.md"
          
          echo "# Build Summary" > $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          echo "**Build Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $SUMMARY_FILE
          echo "**Commit:** ${{ github.sha }}" >> $SUMMARY_FILE
          echo "**Branch:** ${{ github.ref_name }}" >> $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          
          echo "## Build Artifacts with MD5 Checksums" >> $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          
          # Windows artifacts
          echo "### Windows" >> $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          echo "| File | Size | MD5 |" >> $SUMMARY_FILE
          echo "|------|------|-----|" >> $SUMMARY_FILE
          
          find artifacts/windows-build -type f \( -name "*.exe" -o -name "*.msi" \) 2>/dev/null | while read f; do
            if [ -f "$f" ]; then
              filename=$(basename "$f")
              filesize=$(du -h "$f" | cut -f1)
              md5sum=$(md5sum "$f" | cut -d' ' -f1)
              echo "| $filename | $filesize | \`$md5sum\` |" >> $SUMMARY_FILE
            fi
          done || echo "| No Windows artifacts found | - | - |" >> $SUMMARY_FILE
          
          echo "" >> $SUMMARY_FILE
          
          # macOS artifacts
          echo "### macOS" >> $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          echo "| File | Size | MD5 |" >> $SUMMARY_FILE
          echo "|------|------|-----|" >> $SUMMARY_FILE
          
          find artifacts/macos-build -type f \( -name "*.dmg" -o -name "*.app.tar.gz" -o -name "*.app" \) 2>/dev/null | while read f; do
            if [ -f "$f" ]; then
              filename=$(basename "$f")
              filesize=$(du -h "$f" | cut -f1)
              md5sum=$(md5sum "$f" | cut -d' ' -f1)
              echo "| $filename | $filesize | \`$md5sum\` |" >> $SUMMARY_FILE
            fi
          done || echo "| No macOS artifacts found | - | - |" >> $SUMMARY_FILE
          
          echo "" >> $SUMMARY_FILE
          
          # Generate checksums file
          echo "## Checksums File" >> $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          echo "A \`checksums.md5\` file has been generated with all MD5 hashes." >> $SUMMARY_FILE
          
          # Create MD5 checksums file
          CHECKSUM_FILE="checksums.md5"
          echo "# MD5 Checksums for Bubblefish Build" > $CHECKSUM_FILE
          echo "# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $CHECKSUM_FILE
          echo "" >> $CHECKSUM_FILE
          
          find artifacts -type f \( -name "*.exe" -o -name "*.msi" -o -name "*.dmg" -o -name "*.app.tar.gz" \) 2>/dev/null | while read f; do
            if [ -f "$f" ]; then
              md5sum "$f" | sed "s|artifacts/[^/]*/||" >> $CHECKSUM_FILE
            fi
          done
          
          # Display summary in job output
          cat $SUMMARY_FILE
          
          # Also create GitHub step summary
          cat $SUMMARY_FILE >> $GITHUB_STEP_SUMMARY

      - name: Upload summary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-summary
          path: |
            build-summary.md
            checksums.md5
          retention-days: 30

      - name: Add summary to release (if release)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build-summary.md
            checksums.md5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}